### ISSUE TITLE
Rewrite URL in a location bar when click links

### ISSUE THREAD

**Issue by mizzy** [walter-cd/walter-server#10]
For example, I access the top of walter-sesrver (assume http://localhost:8080/), then I click the link of the one of the builds, the URL in a location bar of a browser is still http://localhost:8080/ . So I cannot use a browser back button.

Changing URL in a location bar when we click links is better.

@gerryhocks Can you implement this, please ?

**Comment by gerryhocks** [comment]
Yes of course. 

I'm not 100% sure but I think the only way to implement this is to refresh the whole page for each click, essentially visiting the site again. But I will investigate and see what can be done.

**Comment by mizzy** [comment]
Thanks for quick reply!

How about this ?
http://blog.falafel.com/fixing-back-button-simple-spa-behavior-using-location-hash/

**Comment by gerryhocks** [comment]
Looks suitable! Thanks! :)

**Comment by mizzy** [comment]
You're welcome :smile:

**Comment by gerryhocks** [comment]
I've pushed changes that should fix this issue and make the browser URL track the current view.

Could you please test this change?

**Comment by mizzy** [comment]
Thanks! I will check it.

**Comment by mizzy** [comment]
LGTM! Thanks a lot!
